spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=FALSE&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    logging:
    level:
    com.example.bdatabaserole.mapper: debug
